%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\_git_work\_MATLAB\802.11ad-ay-phy-sim\802.11ad-ay-phy-sim\nonUniformConst64_cr12.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 20-Jul-2020 13:42:53

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:F65";

% Specify column names and types
opts.VariableNames = ["bitlabeldecbin", "VarName2", "constellpoint", "re", "im", "im_unit"];
opts.SelectedVariableNames = ["bitlabeldecbin", "VarName2", "constellpoint", "re", "im", "im_unit"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Import the data
nonUniformConst64cr58 = readtable("D:\_git_work\_MATLAB\802.11ad-ay-phy-sim\802.11ad-ay-phy-sim\nonUniformConst64_cr58.xlsx", opts, "UseExcel", false);

%% Convert to output type
nonUniformConst64cr58 = table2array(nonUniformConst64cr58);

%% Clear temporary variables
clear opts